# https://www.schemastore.org/github-action.json
name: "TypeScript Action"
# Description must be less than 125 characters.
description: "TypeScript Action Template"
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  milliseconds:
    description: "Your input description here"
    default: "1000"

outputs:
  time:
    description: "Your output description here"

runs:
  using: "node24"
  main: "dist/index.js"
