# https://www.schemastore.org/github-action.json
name: "TypeScript Action"
# Description must be less than 125 characters.
description: "TypeScript Action Template"
author: "Shane"

branding:
  icon: "type"
  color: "green"

inputs:
  tag:
    description: "Tag to Create or Update"
  summary:
    description: "Add Summary to Job"
    default: "true"
  token:
    description: "GitHub Token"
    default: ${{ github.token }}

outputs:
  sha:
    description: "Tag Hash"

runs:
  using: "node24"
  main: "dist/index.js"
